CREATE TABLE IF NOT EXISTS roles (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT    NOT NULL UNIQUE,
    color       TEXT,
    permissions BIGINT  NOT NULL DEFAULT 0,
    position    INTEGER NOT NULL DEFAULT 0,
    is_default  INTEGER NOT NULL DEFAULT 0
);

INSERT INTO roles (id, name, color, permissions, position, is_default)
VALUES
    (1, 'Owner',     '#E74C3C', 2147483647, 100, 0),
    (2, 'Admin',     '#F39C12', 1073741823,  80, 0),
    (3, 'Moderator', '#3498DB',    1048575,  60, 0),
    (4, 'Member',    NULL,            7779,  40, 1)
ON CONFLICT (id) DO NOTHING;

SELECT setval(
    pg_get_serial_sequence('roles', 'id'),
    GREATEST(COALESCE((SELECT MAX(id) FROM roles), 1), 1),
    true
);

CREATE TABLE IF NOT EXISTS users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    TEXT    NOT NULL,
    password    TEXT    NOT NULL,
    avatar      TEXT,
    role_id     BIGINT  NOT NULL DEFAULT 4 REFERENCES roles(id),
    totp_secret TEXT,
    status      TEXT    NOT NULL DEFAULT 'offline',
    created_at  TEXT    NOT NULL DEFAULT (to_char(timezone('utc', now()), 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
    last_seen   TEXT,
    banned      INTEGER NOT NULL DEFAULT 0,
    ban_reason  TEXT,
    ban_expires TEXT
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_users_username_lower ON users (LOWER(username));

CREATE TABLE IF NOT EXISTS sessions (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token      TEXT   NOT NULL UNIQUE,
    device     TEXT,
    ip_address TEXT,
    created_at TEXT   NOT NULL DEFAULT (to_char(timezone('utc', now()), 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
    last_used  TEXT   NOT NULL DEFAULT (to_char(timezone('utc', now()), 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
    expires_at TEXT   NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_sessions_token ON sessions(token);
CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_id);

CREATE TABLE IF NOT EXISTS channels (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             TEXT    NOT NULL,
    type             TEXT    NOT NULL DEFAULT 'text',
    category         TEXT,
    topic            TEXT,
    position         INTEGER NOT NULL DEFAULT 0,
    slow_mode        INTEGER NOT NULL DEFAULT 0,
    archived         INTEGER NOT NULL DEFAULT 0,
    created_at       TEXT    NOT NULL DEFAULT (to_char(timezone('utc', now()), 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
    voice_max_users  INTEGER NOT NULL DEFAULT 0,
    voice_quality    TEXT,
    mixing_threshold INTEGER,
    voice_max_video  INTEGER NOT NULL DEFAULT 25
);

CREATE TABLE IF NOT EXISTS channel_overrides (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_id BIGINT NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
    role_id    BIGINT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    allow      BIGINT NOT NULL DEFAULT 0,
    deny       BIGINT NOT NULL DEFAULT 0,
    UNIQUE(channel_id, role_id)
);

CREATE INDEX IF NOT EXISTS idx_channel_overrides_channel_role
    ON channel_overrides(channel_id, role_id);

CREATE TABLE IF NOT EXISTS messages (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_id     BIGINT NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
    user_id        BIGINT NOT NULL REFERENCES users(id),
    content        TEXT   NOT NULL,
    reply_to       BIGINT REFERENCES messages(id) ON DELETE SET NULL,
    edited_at      TEXT,
    deleted        INTEGER NOT NULL DEFAULT 0,
    pinned         INTEGER NOT NULL DEFAULT 0,
    timestamp      TEXT    NOT NULL DEFAULT (to_char(timezone('utc', now()), 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
    search_vector  tsvector GENERATED ALWAYS AS (to_tsvector('simple', COALESCE(content, ''))) STORED
);

CREATE INDEX IF NOT EXISTS idx_messages_channel ON messages(channel_id, id DESC);
CREATE INDEX IF NOT EXISTS idx_messages_user ON messages(user_id);
CREATE INDEX IF NOT EXISTS idx_messages_search_vector ON messages USING GIN (search_vector);

CREATE TABLE IF NOT EXISTS attachments (
    id          TEXT PRIMARY KEY,
    message_id  BIGINT REFERENCES messages(id) ON DELETE CASCADE,
    filename    TEXT   NOT NULL,
    stored_as   TEXT   NOT NULL,
    mime_type   TEXT   NOT NULL,
    size        BIGINT NOT NULL,
    uploaded_at TEXT   NOT NULL DEFAULT (to_char(timezone('utc', now()), 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
    width       INTEGER,
    height      INTEGER,
    uploader_id BIGINT REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_attachments_uploader ON attachments(uploader_id);

CREATE TABLE IF NOT EXISTS reactions (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id BIGINT NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
    user_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    emoji      TEXT   NOT NULL,
    UNIQUE(message_id, user_id, emoji)
);

CREATE TABLE IF NOT EXISTS invites (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        TEXT   NOT NULL UNIQUE,
    created_by  BIGINT NOT NULL REFERENCES users(id),
    redeemed_by BIGINT REFERENCES users(id),
    max_uses    INTEGER,
    use_count   INTEGER NOT NULL DEFAULT 0,
    expires_at  TEXT,
    created_at  TEXT   NOT NULL DEFAULT (to_char(timezone('utc', now()), 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
    revoked     INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_invites_code ON invites(code);

CREATE TABLE IF NOT EXISTS read_states (
    user_id         BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    channel_id      BIGINT NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
    last_message_id BIGINT NOT NULL DEFAULT 0,
    mention_count   INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (user_id, channel_id)
);

CREATE TABLE IF NOT EXISTS audit_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id    BIGINT  NOT NULL DEFAULT 0,
    action      TEXT    NOT NULL,
    target_type TEXT    NOT NULL DEFAULT '',
    target_id   BIGINT  NOT NULL DEFAULT 0,
    detail      TEXT    NOT NULL DEFAULT '',
    created_at  TEXT    NOT NULL DEFAULT (to_char(timezone('utc', now()), 'YYYY-MM-DD"T"HH24:MI:SS"Z"'))
);

CREATE INDEX IF NOT EXISTS idx_audit_timestamp ON audit_log(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_log_actor ON audit_log(actor_id);

CREATE TABLE IF NOT EXISTS login_attempts (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ip_address TEXT    NOT NULL,
    username   TEXT,
    success    INTEGER NOT NULL DEFAULT 0,
    timestamp  TEXT    NOT NULL DEFAULT (to_char(timezone('utc', now()), 'YYYY-MM-DD"T"HH24:MI:SS"Z"'))
);

CREATE INDEX IF NOT EXISTS idx_login_ip ON login_attempts(ip_address, timestamp);

CREATE TABLE IF NOT EXISTS settings (
    key   TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

INSERT INTO settings (key, value) VALUES
    ('server_name',        'OwnCord Server'),
    ('server_icon',        ''),
    ('motd',               'Welcome!'),
    ('max_upload_bytes',   '26214400'),
    ('voice_quality',      'high'),
    ('require_2fa',        '0'),
    ('registration_open',  '0'),
    ('backup_schedule',    'daily'),
    ('backup_retention',   '7'),
    ('schema_version',     '1')
ON CONFLICT (key) DO NOTHING;

CREATE TABLE IF NOT EXISTS emoji (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shortcode   TEXT   NOT NULL UNIQUE,
    filename    TEXT   NOT NULL,
    uploaded_by BIGINT NOT NULL REFERENCES users(id),
    created_at  TEXT   NOT NULL DEFAULT (to_char(timezone('utc', now()), 'YYYY-MM-DD"T"HH24:MI:SS"Z"'))
);

CREATE TABLE IF NOT EXISTS sounds (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT   NOT NULL,
    filename    TEXT   NOT NULL,
    duration_ms INTEGER NOT NULL,
    uploaded_by BIGINT NOT NULL REFERENCES users(id),
    created_at  TEXT   NOT NULL DEFAULT (to_char(timezone('utc', now()), 'YYYY-MM-DD"T"HH24:MI:SS"Z"'))
);

CREATE TABLE IF NOT EXISTS voice_states (
    user_id      BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    channel_id   BIGINT  NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
    muted        INTEGER NOT NULL DEFAULT 0,
    deafened     INTEGER NOT NULL DEFAULT 0,
    speaking     INTEGER NOT NULL DEFAULT 0,
    joined_at    TEXT    NOT NULL DEFAULT (to_char(timezone('utc', now()), 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
    camera       INTEGER NOT NULL DEFAULT 0,
    screenshare  INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_voice_states_channel ON voice_states(channel_id);

CREATE TABLE IF NOT EXISTS dm_participants (
    channel_id BIGINT NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
    user_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    PRIMARY KEY (channel_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_dm_participants_user ON dm_participants(user_id);

CREATE TABLE IF NOT EXISTS dm_open_state (
    user_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    channel_id BIGINT NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
    opened_at  TEXT   NOT NULL DEFAULT (to_char(timezone('utc', now()), 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
    PRIMARY KEY (user_id, channel_id)
);

CREATE TABLE IF NOT EXISTS rate_lockouts (
    key        TEXT PRIMARY KEY,
    expires_at TEXT NOT NULL
);
